"""add users table

Revision ID: 11b0ace100c9
Revises: b9f799cf55e8
Create Date: 2026-07-16 23:56:14.408796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate compiled created_at's server_default against the dialect that
# generated this migration (SQLite), which renders the SQLite-specific
# '(CURRENT_TIMESTAMP)'. Production runs Postgres via asyncpg, so this is
# hand-edited to the bare ANSI form both dialects accept identically — the
# same correction the initial migration needed.
_CREATED_AT_DEFAULT = sa.text("CURRENT_TIMESTAMP")

# revision identifiers, used by Alembic.
revision: str = '11b0ace100c9'
down_revision: Union[str, Sequence[str], None] = 'b9f799cf55e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('organisation', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_CREATED_AT_DEFAULT, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
