"""initial schema

Revision ID: b9f799cf55e8
Revises:
Create Date: 2026-07-16 17:38:28.852688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate captured created_at's server_default by compiling
# func.now() against whichever dialect generated this migration (SQLite),
# which rendered as the SQLite-specific '(CURRENT_TIMESTAMP)'. Production
# runs Postgres via asyncpg, so this is hand-edited to the bare ANSI
# CURRENT_TIMESTAMP both dialects accept identically.
_CREATED_AT_DEFAULT = sa.text("CURRENT_TIMESTAMP")


# revision identifiers, used by Alembic.
revision: str = 'b9f799cf55e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('primary_cause', sa.String(length=128), nullable=False),
    sa.Column('secondary_causes', sa.JSON(), nullable=False),
    sa.Column('predicted_event', sa.String(length=128), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_CREATED_AT_DEFAULT, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_vehicle_id'), 'risk_events', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_vehicle_id'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
